services:
  web:
    build: ./app
    container_name: d3-web
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      REDIS_HOST: cache
      REDIS_PORT: "6379"
    depends_on:
      - db
      - cache
  db:
    image: postgres:16-alpine
    container_name: d3-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - db-data:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    container_name: d3-cache
volumes:
  db-data:
